[package]
name = "rust-gtfs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
chrono-tz = "0.10.1"
colored = "3.0.0"
csv = "1.3.1"
curl = "0.4.47"
hex_color = "3.0.0"
pipe = "0.4.0"
zip = "2.2.2"
